### ISSUE TITLE
Where is bert-classification-generic-story.py?

### ISSUE THREAD

**Issue by ziweiji** [witerforcing/WriterForcing#1]
In evaluate_attributes/evaluate_story_cloze.py 
BERT_COMMAND = "python ../bert-classification-generic-story.py" \
                   " --task_name DST" \
                   " --do_eval --do_lower_case " \
                   "--data_dir ." \
                   " --input_train_file_name " + stroy_cloze_file + " --input_test_file_name " + stroy_cloze_file  +\
                   " --output_results_file_name eval_results.txt --output_predictions_file_name predictions.txt" \
                   " --bert_model bert-base-uncased" \
                   " --max_seq_length 200" \
                   " --train_batch_size 16 " \
                   "--learning_rate 2e-5" \
                   " --num_train_epochs 3.0 " \
                   "--output_dir ../../ --num_classes 2 --device_num " + str(args.gpu)

Can't find file ../bert-classification-generic-story.py

**Comment by vinayshekharcmu** [comment]
We have added the file in the repo.

**Comment by ziweiji** [comment]
> We have added the file in the repo.

Thanks!
